### ISSUE TITLE
Grammar Nazi

### ISSUE THREAD

**Issue by Aschen** [Mickaeldicurzio/Cv-2017-Static#1]
Dévelopeur Web Junior -> Développeur Web Junior
Entreprise Actuel -> Entreprise Actuelle
m'ont permis -> m'a permis (c'est ta participation qui a permis)
auprès d'un oratoire -> auprès d'un auditoire

Très sympa le site je trouve sinon :-) 
Un lien soundcloud éventuellement ?

**Comment by Mickaeldicurzio** [comment]
mdrrr je vient de repush et il est en anglais... après j'en suis à même pas
un 5éme pour le moment :D
je vais faire un lien dans la partie perso du site^^ après je vais faire un
site spé Neptune plus tard :D
ca va toi?

**Comment by Aschen** [comment]
Ouais j'avais remarqué tkt :p 
Yes j'espère bien ;) Intégration du player soundcloud et tout !
genre les mecs qui tapent la discutent dans le commentaires github ^^
